### PR TITLE
a few improvements

### PR DESCRIPTION
**Pull request by maciejsszmigiero**
Thanks for establishing this repository Jörg!

This pull request includes few improvements to the bootloader.

Included are three small build improvements:
* Don't try to setup ports which don't exist on target uC,
* Avoid build error on binutils without "avr" size format patch,
* Don't build haveChar() function when it is not going to be used (avoids a build warning).

Also included is watchdog pinging support (needed in case watchdog is permanently enabled via an appropriate fuse bit for an extra reliability) and one small cleanup (declaring binary integer constants using binary prefix instead of using special macro in configuration file).

The most important change, however, is ability to have configuration separate from the code.
This allows an alternative workflow where different configurations can be built from one source tree (like a release and debug version for example).
It also makes contributing back a little easier since the user would no longer need to separate what constitute just configuration changes from new or changed functionality that he or she wants to contribute in the same files.
Existing workflow via a local branch is unaffected by this change.

Please see individual commit messages for details.

### CODE REVIEW

**Comment by maciejsszmigiero** [comment]
Added a fix for EEPROM reading / writing at nonzero base address.

All these changes were tested on Atmega 1284.

**Comment by joede** [comment]
Thanks for the changes. I need some time to proof the backward compatibility with some of my older projects.

**Comment by maciejsszmigiero** [comment]
Added an ability to have separate build tree(s) from the source one.

This is purely a Makefile (and docs) change, the actual source code is not touched.
Also, it is backwards-compatible by default.

**Comment by joede** [comment]
Thanks for your changes. I try to look at them this weekend or not later than next week.

**Comment by maciejsszmigiero** [comment]
Thanks Jörg.

**Comment by joede** [comment]
I've merged your changes into the branch "develop". Feel free to update your fork...

I have to find some time to test my legacy code with mega128 and mega2560 MCUs to be sure the bootloader is still running. ;-)

I've never handled a "pull request" before, so I hope all is OK. I've used the Git command line to pull and merge your code.

**Comment by maciejsszmigiero** [comment]
It looks like everything is fine with the merge - I've just built your "develop" branch with a config for my
project and the assembler listing is exactly the same as it was from my "improvements" branch.

I will remove my forked repository after some time has passed since the last commit (as I do with other
projects I contribute to), so I don't trash GitHub and search engines with unnecessary clones -
I usually keep my bootloader config file(s) in a master repository for a particular project.

Overall, I would like to say thanks to you once again for establishing and managing repository for this bootloader!

**Comment by joede** [comment]
I'm happy to see that this repo is used and it helps someone. So every PR is welcome, even if my spare time is limited so that merging takes a while.
Thanks for your code.

**Pull request closed without merging**
